brasileirao = ('Botafogo', 'Palmeiras', 'Flamengo', 'Atletico-MG', 'Fluminense', 'Grêmio', 'Athletico-PR', 'São Paulo', 'Cruzeiro', 'Internacional', 'Fortaleza', 'Bragantino', 'Santos', 'Cuiabá', 'Bahia', 'Corinthians', 'Goias', 'America-MG', 'Vasco da Gama', 'Coritiba')
print(f'Os times que estão participando do Brasileirão Serie A são {brasileirao}')
print('-=' * 20)
print(f'Os cinco primeiros são: {brasileirao[:5]}')
print('-=' * 20)
print(f'Os cinco últimos são: {brasileirao[-1]}, {brasileirao[-2]}', {brasileirao[-3]}, {brasileirao[-4]}, {brasileirao[-5]})
print('-=' * 20)
print(f'Time em ordem alfabética: {sorted(brasileirao)}')
print(f'Santos está na {brasileirao.index()}')